//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook
    {
        public int bookID { get; set; }
        public string bookName { get; set; }
        public Nullable<int> catID { get; set; }
        public Nullable<int> authID { get; set; }
        public Nullable<int> pubId { get; set; }
        public string bookContents { get; set; }
        public Nullable<int> bookPages { get; set; }
        public string bookEdition { get; set; }
        public string ISBN_Number { get; set; }
    
        public virtual tblAuthor tblAuthor { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblPublisher tblPublisher { get; set; }
    }
}
